### ISSUE TITLE
Dynamo_Toolkit: Support for multiple PolyCurves for BuildingElement

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Dynamo_UI#111]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by albinber** [comment]
Having reviewed this issue, it is no longer relevant to the state of Dynamo_UI and is being closed for the 2024 clean up
