### ISSUE TITLE
Dynamo_Toolkit: .dll version 1.2.0

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_UI#138]
Currently we are using Dynamo 1.3.4.6666 however I noticed that our library reference 1.2.0
Should not we update to correct version ?

![image](https://user-images.githubusercontent.com/26113670/58085935-9aec8680-7bb5-11e9-9890-12ae1fec522b.png)

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak,

I believe it should be 1.3.4 however it probably have minor influence on Dynamo behaviour. The issues will start with 2.0 and above.

**Comment by FraserGreenroyd** [comment]
We no longer support Dynamo 1.3 so this issue is null and void.
