### ISSUE TITLE
Dynamo_Toolkit: Dictionary Issue

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_UI#172]
#### Description:

When I generate Dictionay in GH it looks like that
![image](https://user-images.githubusercontent.com/26113670/65944764-5c4fbe00-e42a-11e9-98cb-2a78e53ce314.png)

when trying to replicate in Dynamo
can not get it on a simple list
![image](https://user-images.githubusercontent.com/26113670/65944810-6ec9f780-e42a-11e9-8f97-207c210aaced.png)

when trying to generate Sub-list it runs but does not return a dictionary
![image](https://user-images.githubusercontent.com/26113670/65944856-873a1200-e42a-11e9-8afc-5b80f2eef49c.png)
please note that on explode we have a length not `name`
 How to set it up?
I will add @IsakNaslundBh @adecler maybe they can help

here is Dynamo [documentation on this](https://primer.dynamobim.org/09_Dictionaries/9-1_What-is-a-dictionary.html) 

#### Expected behaviour:

output dictionary

**Comment by albinber** [comment]
Having reviewed this issue, it is no longer relevant to the state of Dynamo_UI and is being closed for the 2024 clean up.
