### ISSUE TITLE
Dynamo_Toolkit: Copy the files to 2.1 and 2.2 folders

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_UI#206]
#### Description:

Currently the only Dynamo 2.X folders to which the files are copied are 2.0 and 2.3. It would be good to add 2.1 and 2.2 as well, it would be even better to copy the assemblies to _every_ folder in Dynamo dir that starts with 2. prefix (as long as the code works on all versions ofc).

**Comment by awakeman** [comment]
The duplication of all assemblies in dynamo has grown a bunch with #209, solving this issue before solving #135 will only make that problem worse (scaling it to a total of 10 copies for dynamo alone)

**Comment by pawelbaran** [comment]
@adecler following our discussion, I have checked and Dynamo does not pick the assemblies from lower versions. Which means that we need to have a separate copy per 2.X, where maximum X is atm 6.

**Comment by FraserGreenroyd** [comment]
Code should copy only to the folders for versions we explicitly support to avoid the issue of code not working on a given version without testing, so I would say this is a non-issue in our current framework.
