### ISSUE TITLE
Create Geometry.Face object error using Dynamo

### ISSUE THREAD

**Issue by michaellisitsa** [BHoM/Dynamo_UI#272]
#### Description:
It appears that when creating a `BH.oM.Geometry.Face` object which takes int32 indices, `Convert.ToDesignScript` is run and uses the incorrect overloaded method (it choose the arguments as `BH.oM.Geometry.Point` as there is no method with `Geometry.Faces` arguments).

The output of the node is 'null'

Unsure if this issue is related to [https://github.com/BHoM/MidasCivil_Toolkit/issues/254#issue-708865982](url)

#### Steps to reproduce:
- Create a Face object using the "CreateObject" node
- Input integers between 0 to 3 into arguments a to d.
- Optionally, attach the face object to a `Geometry.Mesh` node which takes "vertices" and "faces" as arguments, although this doesn't change the error.
![image](https://user-images.githubusercontent.com/58811856/95990104-d35dc600-0e76-11eb-97b3-002d2ac6ae2e.png)

#### Expected behaviour:
- A face object is created
- This can be used in Midas_Civil to input a mesh, since Midas doesn't accept panels.
![image](https://user-images.githubusercontent.com/58811856/95990529-5ed75700-0e77-11eb-9d4f-9db61201969d.png)

#### Setup:
- BHoM Version 3.3.beta.0
- Revit 2019 and Dynamo 2.0.4
- Windows 10 version 1709

**Comment by albinber** [comment]
Having reviewed this issue, it is no longer relevant to the state of Dynamo_UI and is being closed for the 2024 clean up.
