### ISSUE TITLE
Package not showing up in any Revit and Dynamo Version

### ISSUE THREAD

**Issue by markb343** [BHoM/Dynamo_UI#304]
#### Description:
After installing BHom, the plug-in appears in revit, but when I go to open it in Dynamo I cannot find it anywhere. I have searched for packages, looked at other online forums, downloaded other folders and searched for them in the add-ins, cannot find anything to resolve this issue.

#### Steps to reproduce:
Download BHOM and install it to revit 2020-2022.

#### Expected behaviour:
To see the BHoM package in the Dynamo side bar.

**Comment by albinber** [comment]
Having reviewed this issue, it is no longer relevant to the state of Dynamo_UI and is being closed for the 2024 clean up.
