### ISSUE TITLE
BHoM missing from Dynamo Add-ons

### ISSUE THREAD

**Issue by BristolCAD** [BHoM/Dynamo_UI#319]
#### Description:
Hi, apologies if this has been discussed elsewhere. 

I have downloaded and installed BHoM to Revit 2023. The plugin loads in Revit, I have activated it. When I load Dynamo, BHoM is supposed to be in the bar on the left hand side under Add-ons but it is not present. 

I've also tried copying files to this location: C:\Users\USERNAME\AppData\Roaming\Dynamo\Dynamo Revit\2.13\packages but again, nothing loads.

Under this location C:\Users\USERNAME\AppData\Roaming\Dynamo\Dynamo Revit\2.13\packages all the BHoM package files (bin, extra, pkg.json) seem to be in the 2.3 folder rather than the 2.13. But moving the files to 2.13 just causes Dynamo to crash upon opening.

Hoping someone might be able to shed some light and many thanks.

#### Steps to reproduce:
Install BHoM to Revit 2023, activate, run Dynamo, start new Dynamo file

#### Expected behaviour:
BHom package/tools show up in Dynamo under the Add-ons tab

#### Test file(s):
No files available

**Comment by FraserGreenroyd** [comment]
Hi @BristolCAD , sorry for the long wait on a reply, it's taken me a while to get around to looking at the various Dynamo issues.

I've spoken with @pawelbaran and some of the others in the team, and we've managed to conclude the following:

 - BHoM for Dynamo is unlikely to work in versions of Dynamo shipped with Revit later than 2021, as this was the last version of Dynamo for Revit tested by us
 - We have vague memories of 2.13 Dynamo being very buggy to work with, and opting to skip straight to 2.3 in 2021 with unexplained crashes on Dynamo that we struggled to trace back

We opted therefore to put more focus on interoperability with model controls via [Revit_Toolkit](https://github.com/BHoM/Revit_Toolkit) and improve UX within [Grasshopper](https://github.com/BHoM/Grasshopper_UI) and [Excel](https://github.com/BHoM/Excel_UI), and have taken the decision with heavy heart to resign support for Dynamo from the 7.0 beta at the end of this year, owing to Dynamo's ongoing issues and our relatively small team of maintainers at present.

We intend to keep this repository open (we're not going to archive it) in the hope that at some stage, we can bring Dynamo back when time permits, but for now, we'll be stopping supporting BHoM for Dynamo at the end of the year with our betas (and @alelom will be updating the website/wikis/documentations appropriately for that).
