### ISSUE TITLE
Dynamo_Toolkit: Provide a preview for all the objects implementing the GetGeometry() method

### ISSUE THREAD

**Issue by adecler** [BHoM/Dynamo_UI#46]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
I have just tested the preview of BHoM objects in Dynamo and it seems to be working fine (at least for the cases that I have tested), so I will close the issue - to be reopened once the issue gets reported again.
